### PR TITLE
Fix delete count bug; add deleted files to stats; correct typos

### PR DESCRIPTION
**Pull request by UplandsDynamic**
Hi,

Thank you for this fantastic script. I was about to write something similar for my photo tagging app, but stumbled upon this and integrated it instead, saving me a lot of time.

I noticed a couple of issues while I was playing about with it and reviewing the code, which I fixed, namely: 1) the deleted image count was erroneously incremented and 2) a few typos.

I also added the deleted file information to the stats output - either just a count, or also with a list of the files deleted, depending upon whether the user had requested verbose logging. Tried to integrate that in the same way that the invalid files are reported, to preserve consistency.

### CODE REVIEW

**Comment by elisemercury** [comment]
Hi @UplandsDynamic,

Thanks a lot for opening the pull request and for your effort in making difPy better! These adjustments are very valuable. I'll include them in the next difPy release.

Again, thanks and all the best,
Elise

**Comment by UplandsDynamic** [comment]
My pleasure, @elisemercury. The effort in making those small changes was as nothing compared to the time this script saved me in not having to code something similar from scratch. All hail open source! 
Let me know if you'd like me to update the README to include a bit about the deletion information in the stats output (I didn't do it before in case you decided against merging that part).
Cheers, 
Dan

**Comment by elisemercury** [comment]
Hi @UplandsDynamic,

Your pull request and adjustments have been merged and added to the new v3.0.9 release. I also updated the README. Thanks again for your contributions!

Cheers,
Elise

**Comment by UplandsDynamic** [comment]
Hi @elisemercury,

That's great! Thank you for merging to main so quickly. I noticed your release of the associated web app too - very slick.

I'm just now having a look at that remaining outstanding issue on your repo, regarding implementation of a preliminary file check, for common image file formats based on file extensions. I'll try to get that done. 

Cheers,
Dan

**Comment by elisemercury** [comment]
Hi @UplandsDynamic,

Thank you so much - that is great! Let's move the conversation to the open issue #60 and I'll share my thoughts around it with you there!

All the best,
Elise

**Pull request merged**
